apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: post-service
      labels:
        app: post-service
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: post-service
      template:
        metadata:
          name: post-service
          labels:
            app: post-service
        spec:
          containers:
            - name: post-service
              image: kazyshi/malurus-post-service:0.5-k8s
              imagePullPolicy: Always
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      name: post-service
      labels:
        app: post-service
    spec:
      selector:
        app: post-service
      ports:
        - port: 8084
          protocol: TCP
          targetPort: 8084