apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 256Mi

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mongo-cm
      labels:
        app: mongo
    data:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mongo
    spec:
      selector:
        matchLabels:
          app: mongo
      template:
        metadata:
          labels:
            app: mongo
        spec:
          containers:
            - name: mongo
              image: mongo
              ports:
                - containerPort: 27017
              envFrom:
                - configMapRef:
                    name: mongo-cm
              volumeMounts:
                - mountPath: /data/db
                  name: mongo
          volumes:
            - name: mongo
              persistentVolumeClaim:
                claimName: mongo-pvc

  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo
    spec:
      selector:
        app: mongo
      ports:
        - port: 27017
          targetPort: 27017
