apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: authentication-service
      labels:
        app: authentication-service
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: authentication-service
      template:
        metadata:
          name: authentication-service
          labels:
            app: authentication-service
        spec:
          containers:
            - name: authentication-service
              image: kazyshi/malurus-authentication-service:0.5-k8s
              imagePullPolicy: Always
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      name: authentication-service
      labels:
        app: authentication-service
    spec:
      selector:
        app: authentication-service
      ports:
        - port: 8081
          protocol: TCP
          targetPort: 8081
      sessionAffinity: None
