apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: social-graph-service
      labels:
        app: social-graph-service
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: social-graph-service
      template:
        metadata:
          name: social-graph-service
          labels:
            app: social-graph-service
        spec:
          containers:
            - name: social-graph-service
              image: kazyshi/malurus-social-graph-service:0.5-k8s
              imagePullPolicy: Always
          restartPolicy: Always

  - apiVersion: v1
    kind: Service
    metadata:
      name: social-graph-service
      labels:
        app: social-graph-service
    spec:
      selector:
        app: social-graph-service
      ports:
        - port: 8083
          protocol: TCP
          targetPort: 8083